name: Notify assignees when their card moves between columns

on:
  project_card:
      types: [moved]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/project-card-moved-notification@1.0
